#ifndef __TI_MATHLIB__
#define __TI_MATHLIB__

#include <acosdp.h> 
#include <acoshdp.h> 
#include <acoshsp.h>
#include <acossp.h>
#include <asindp.h>
#include <asinhdp.h>
#include <asinhsp.h>
#include <asinsp.h>
#include <atan2dp.h>
#include <atan2sp.h>
#include <atandp.h>
#include <atanhdp.h>
#include <atanhsp.h>
#include <atansp.h>
#include <cosdp.h>
#include <coshdp.h>
#include <coshsp.h>
#include <cossp.h>
#include <divdp.h>
#include <divsp.h>
#include <exp10dp.h>
#include <exp10sp.h>
#include <exp2dp.h>
#include <exp2sp.h>
#include <expdp.h>
#include <expsp.h>
#include <log10dp.h>
#include <log10sp.h>
#include <log2dp.h>
#include <log2sp.h>
#include <logdp.h>
#include <logsp.h>
#include <mathlib.h>
#include <powdp.h>
#include <powsp.h>
#include <recipdp.h>
#include <recipsp.h>
#include <rsqrtdp.h>
#include <rsqrtsp.h>
#include <sindp.h>
#include <sinhdp.h>
#include <sinhsp.h>
#include <sinsp.h>
#include <sqrtdp.h>
#include <sqrtsp.h>
#include <tandp.h>
#include <tanhdp.h>
#include <tanhsp.h>
#include <tansp.h>

#endif /* __TI_MATHLIB__ */ 
