function %aotlist_p(obj)
    mprintf("AO task object\n")
    mprintf("   .start() - start task\n")
    mprintf("   .init() - initialize AO task\n")
    mprintf("   .write() - writes AO data\n")
    mprintf("   .stop() - stops task\n")
    mprintf("   .isDone() - checks if task is done\n")
    mprintf("   .waitUntilDone() - blocks until task is done\n")
    mprintf("   .setTrigger() - confiures AO task trigger\n")
endfunction
